version: '3.9'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: sh -c "npm run seed && npm run dev"
  mongo:
    image: mongo:5
    container_name: ticket-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
